---
# vars file for {{ role_name }}
ubuntu_sudo_username: "{{ ansible_user }}"
ubuntu_default_editor_path: "/usr/bin/vim.tiny"
###############################################################################################################################################################
