---
- name: "Mount NFS shares for Controller"
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: "{{ item.options }}"
    state: mounted
  loop: "{{ controller_nfs_mounts }}"
