---
# vars file for {{ role_name }}
host_provision_iso_os: "{{ host_provision_os }}" # I think this will work.
host_provision_iso_iso_dir: "{{ hostvars['controller'].provision.vars.iso_root }}"
host_provision_iso_ssh_pub_key_path: "{{ ansible_ssh_private_key_file }}.pub"
host_provision_iso_hostname: "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
host_provision_iso_networks: "{{ hostvars[inventory_hostname].provision.hardware.networks | default([]) }}"
host_provision_iso_dns_servers: "{{ hostvars[inventory_hostname].provision.hardware.dns.servers | default([]) }}"
host_provision_iso_proxy_protocol: "{{ ext_apt_proxy_protocol | default(host_provision_iso_proxy_protocol_default) }}"
host_provision_iso_proxy_host: "{{ ext_apt_proxy_host | default(host_provision_iso_proxy_host_default) }}"
host_provision_iso_proxy_port: "{{ ext_apt_proxy_port | default(host_provision_iso_proxy_port_default) }}"

# These are purposefully commented out. I want the app to fail if any of these are not initialized.

# host_provision_iso_file_name: "<DEFAULT>"
# host_provision_iso_base_url: "<DEFAULT>"
# host_provision_iso_url: "<DEFAULT>"
# host_provision_iso_iso_dir: "<DEFAULT>"
# host_provision_iso_path: "<DEFAULT>"
# host_provision_iso_mode: "<DEFAULT>"
# host_provision_iso_checksum: "<DEFAULT>"
# host_provision_iso_tmp_dir: "<DEFAULT>"
# host_provision_iso_tmp_iso_dir: "<DEFAULT>"
# host_provision_iso_nocloud_dir: "<DEFAULT>"
# host_provision_iso_grub_dir: "<DEFAULT>"
# host_provision_iso_nocloud_metadata: "<DEFAULT>"
# host_provision_iso_nocloud_userdata: "<DEFAULT>"
# host_provision_iso_boot_grubcfg: "<DEFAULT>"
# host_provision_iso_custom_iso_name: "<DEFAULT>"
# host_provision_iso_custom_iso_path: "<DEFAULT>"
###############################################################################################################################################################
