---
- name: "{{ site_role_action | capitalize }} {{ inventory_hostname }}"
  ansible.builtin.import_tasks: "{{ site_role_action }}.yml"
###############################################################################################################################################################
