---
- name: "Running Host Role for {{ inventory_hostname }}"
  block:
    - name: "Validate appliance cert for {{ inventory_hostname }}"
      when: hostvars[inventory_hostname].provision.type == provision_type_appliance
      block:
        - name: "Get served certificate from {{ inventory_hostname }}"
          community.crypto.get_certificate:
            host: "{{ host_fqdn }}"
            port: "{{ host_validate_port }}"
          register: _appliance_cert

        - name: "Validate certificate issuer and expiry for {{ inventory_hostname }}"
          ansible.builtin.assert:
            that:
              - "_appliance_cert.issuer.O is defined"
              - "_appliance_cert.issuer.O == host_appliance_cert_issuer_org"
              - "not _appliance_cert.expired"

    - name: "Validate port reachability for {{ inventory_hostname }}"
      ansible.builtin.wait_for:
        port: "{{ host_validate_port }}"
        host: "{{ host_fqdn }}"
        delay: 2
        timeout: 10
      when: hostvars[inventory_hostname].provision.type != provision_type_appliance

  rescue:
    - name: "Initial Validation Failed; Performing full validation of {{ inventory_hostname }}"
      ansible.builtin.import_tasks: "tasks/best_task_file.yml"
      vars:
        role_action: "{{ site_role_action }}"