---
# You're going to be all like "oh but "declarative" and it'll be a big thing in your head.
# Don't do it.
# You need the ISO/PXE config BEFORE the VM
# So just let this be procedural. Just fucking let it be.
- name: "Check for VM Existence {{ inventory_hostname }}"
  delegate_to: localhost # So this is required to avoid a weird python interpreter mismatch. I'm not sure why. but its really necessary.
  register: host_vm_info
  vmware.vmware.guest_info:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"
    name: "{{ inventory_hostname }}"
- name: "Set Fact host_is_missing"
  ansible.builtin.set_fact:
    host_is_missing: "{{ host_vm_info.guests | length != 1 }}"
- name: "Host is missing from Manager - Provisioning {{ inventory_hostname }}"
  when: host_should_reprovision and host_is_missing
  block:
    # provision_vm_vmware.yml now handles everything:
    # create VM → get MAC → run host_provision role → power on → wait install → cleanup
    - name: "Provision {{ inventory_hostname }}"
      ansible.builtin.import_tasks: "tasks/best_task_file.yml"
      vars:
        role_action: "provision"
- name: "Validating Host is PoweredOn {{ inventory_hostname }}"
  delegate_to: localhost # So this is required to avoid a weird python interpreter mismatch. I'm not sure why. but its really necessary.
  community.vmware.vmware_guest:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"
    name: "{{ inventory_hostname }}"
    state: poweredon
- name: "Post PowerOn validation of {{ inventory_hostname }}"
  ansible.builtin.wait_for:
    port: "{{ host_validate_port }}"
    host: "{{ host_fqdn }}"
    search_regex: "OpenSSH"
    delay: 2 # 2 second queries
    timeout: 300 #5 minutes wait
- name: "The Handshake: Adding to known_hosts {{ host_fqdn }}"
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.known_hosts:
    name: "{{ host_fqdn}}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 ' + host_fqdn) }}"
    state: present
