---
# defaults file for iso
iso_mode_default: '0644'
###############################################################################################################################################################
