---
# vars file for {{ role_name }}
iso_path: "{{ hostvars['controller'].configuration.vars.controller_iso_root }}/{{ iso_file_name }}"
iso_mode: "{{ iso_mode_default }}"
###############################################################################################################################################################
