---
# vars file for {{ role_name }}
iso_path: "{{ hostvars['controller'].provision.vars.iso_root }}/{{ iso_file_name }}"
iso_mode: "{{ iso_mode_default }}"
###############################################################################################################################################################
