---
- name: "Check if UniFi OS Server is installed"
  ansible.builtin.service_facts:
  register: _unifi_os_facts

- name: "Install UniFi OS Server"
  when: (_unifi_os_service_name + '.service') not in ansible_facts.services or
    ansible_facts.services[_unifi_os_service_name + '.service'].state != 'running'
  block:
    - name: "Create installer directory"
      ansible.builtin.file:
        path: "{{ _unifi_os_installer_path | dirname }}"
        state: directory
        mode: "0755"

    - name: "Download UniFi OS Server installer"
      ansible.builtin.get_url:
        url: "{{ _unifi_os_version_url }}"
        dest: "{{ _unifi_os_installer_path }}"
        mode: "0755"

    # - name: "Run UniFi OS Server installer"
    #   ansible.builtin.command: "{{ _unifi_os_installer_path }}"
    #   changed_when: true
# - name: "Ensure UniFi OS Server is enabled and running"
#   ansible.builtin.systemd:
#     name: "{{ _unifi_os_service_name }}"
#     state: started
#     enabled: true
###############################################################################################################################################################
