---
# defaults file for host_provision
host_provision_mode_default: '0644'
host_provision_template_mode_default: '0755'
###############################################################################################################################################################
