---
ca_cert_import_dest: "{{ hostvars[inventory_hostname] | inventory_entry('import', 'root_ca_cert', 'dest', '', contains=ca_cert_store_dir) }}"
ca_cert_trust_symlink: "/etc/ssl/certs/{{ ca_cert_import_dest | basename | splitext | first }}.pem"
