---
- name: "Build execution order"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Sort items by priority"
      ansible.builtin.set_fact:
        build_items: "{{ groups['all'] | reject('equalto', 'controller') | map('extract', hostvars) | sort(attribute='priority') | map(attribute='inventory_hostname') | list }}"

- name: "Configure Controller"
  hosts: controller
  gather_facts: false
  connection: local
  run_once: true # Cause its the controller
  become: true
  roles:
    - controller

- name: "Validate (and Provision)"
  hosts: "{{ hostvars['localhost'].build_items }}"
  serial: 1
  gather_facts: false
  become: true
  connection: local
  roles:
    - host
  vars:
    site_role_action: "validate"

- name: "Configure"
  hosts: "{{ hostvars['localhost'].build_items }}"
  serial: 1
  gather_facts: true
  become: true
  roles:
    - host
  vars:
    site_role_action: "configure"
