---
host_cert_dir: "{{ export_root }}/{{ inventory_hostname }}"
host_cert_path: "{{ host_cert_dir }}/cert.pem"
host_cert_key_path: "{{ host_cert_dir }}/key.pem"
host_cert_root_path: "{{ hostvars['localhost'].registry | registry_get('root_ca_cert') }}"
host_cert_intermediate_path: "{{ hostvars['localhost'].registry | registry_get('intermediate_ca_cert') }}"
host_cert_chain_path: "{{ host_cert_dir }}/chain.pem"
host_cert_pfx_path: "{{ host_cert_dir }}/cert.pfx"
