---
host_cert_dir: "{{ export_root }}/{{ inventory_hostname }}"
host_cert_path: "{{ host_cert_dir }}/cert.pem"
host_cert_key_path: "{{ host_cert_dir }}/key.pem"
host_cert_root_path: "{{ export_root }}/util/root_ca_cert"
host_cert_intermediate_path: "{{ export_root }}/util/intermediate_ca_cert"
host_cert_chain_path: "{{ host_cert_dir }}/chain.pem"
host_cert_pfx_path: "{{ host_cert_dir }}/cert.pfx"